---

- name: "Including distro-specific variables"
  include_vars: "{{ ansible_distribution }}.yml"

- name: Install gearmand (apt)
  apt: name="{{ gearmand_packages }}" state=latest update_cache=yes cache_valid_time=3600
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install gearmand (dnf)
  dnf: name="{{ gearmand_packages }}" state=latest
  when: ansible_distribution == 'Centos'

- name: Ensure systemd unit override directory is present (Debian/Ubuntu)
  file: 
    path: /etc/systemd/system/{{ gearmand_svcname }}.service.d
    state: directory
    owner: root
    group: root
    mode: 0644
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install config (Debian/Ubuntu)
  template:
    src: gearmand-unit-override.conf
    dest: /etc/systemd/system/{{ gearmand_svcname }}.service.d/mage-override.conf
    mode: 0644
  notify: Restart gearmand (systemd)
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install config (Centos)
  template:
    src: gearmand.conf
    dest: /etc/sysconfig/gearmand
    mode: 0644
  notify: Restart gearmand
  when: ansible_distribution == 'Centos'
  
- name: Start and enable gearmand
  systemd: name="{{ gearmand_svcname }}" state=started enabled=yes daemon_reload=yes
