---
- name: "Include distro-specific variables"
  include_vars: "vars_{{ ansible_distribution }}.yml"

- name: Restart gearmand
  service: name="{{ gearmand_svcname }}" state=restarted
  
- name: Restart gearmand (systemd)
  systemd: name="{{ gearmand_svcname }}" state=restarted daemon_reload=yes
